#  Verifying Basic Data Integrity

Nesse exercício verificamos a integridade dos dados, pois já sabemos que trata-se de uma base de 30 mil contas de créditos, porém precisamos verificar se há 30 mil contas únicas ou se contém duplicatas.

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('default_of_credit_card_clients__courseware_version_1_21_19.xls')

In [3]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

**LIMIT_BAL**: Amount of credit provided (in New Taiwanese (NT) dollar) including individual consumer credit and the family (supplementary) credit.

**SEX**: Gender (1 = male; 2 = female).

**EDUCATION**: Education (1 = graduate school; 2 = university; 3 = high school; 4
= others).

**MARRIAGE**: Marital status (1 = married; 2 = single; 3 = others).

**AGE**: Age (year).

**PAY_1–PAY_6**: A record of past payments. Past monthly payments, recorded
from April to September, are stored in these columns.

**PAY_1**: represents the repayment status in September; PAY_2 is the repayment
status in August; and so on up to PAY_6, which represents the repayment status
in April.
The measurement scale for the repayment status is as follows: -1 = pay duly; 1 =
payment delay for 1 month; 2 = payment delay for 2 months; and so on up to 8 =
payment delay for 8 months; 9 = payment delay for 9 months and above.

**BILL_AMT1–BILL_AMT6**: Bill statement amount (in NT dollar).

**BILL_AMT1** represents the bill statement amount in September; BILL_AMT2
represents the bill statement amount in August; and so on up to BILL_AMT6,
which represents the bill statement amount in April.

**PAY_AMT1–PAY_AMT6**: Amount of previous payment (NT dollar). PAY_AMT1
represents the amount paid in September; PAY_AMT2 represents the amount
paid in August; and so on up to PAY_AMT6, which represents the amount paid
in April.

In [6]:
df.head(5)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  

[5 rows x 25 columns]

Agora que já visualizamos os dados e aparetemente a coluna ID contém valores únicos, preciso analisar todo o dataset para confirmar. 

Nesse caso usaremos o método **.nunique()** para verificar essa informação.

In [7]:
df['ID'].nunique()

29687

In [8]:
df.shape

(30000, 25)

Com essa informação conseguimos observar que há número de ID duplicados, visto que não chega em 30 mil.

Agora perguntas que o livro faz e que já começa a mudar a forma de ver e tentar entender os dados:

**But how much? Is one ID duplicated many
times? How many IDs are duplicated?**

Para responder essas perguntas usaremos o métod **value_counts()** que é similar ao **Group By/Count** no SQL.

In [9]:
id_counts = df['ID'].value_counts()

In [10]:
id_counts.head()

63b20368-1a04    2
51e5ff58-5a0f    2
db903e22-a55a    2
9e6e766d-ba75    2
fa286931-8ded    2
Name: ID, dtype: int64

In [11]:
id_counts.value_counts()

1    29374
2      313
Name: ID, dtype: int64

Agora para ajudar a limpar esses valores duplicados usaremos o que é denominado **Boolean Masks**.

In [12]:
import numpy as np
from  numpy.random import default_rng

In [13]:
rg = default_rng(12345)

In [14]:
random_integers = rg.integers(low=1, high=5, size=100)

In [15]:
random_integers[:5]

array([3, 1, 4, 2, 1], dtype=int64)

In [16]:
is_equal_to_3 = random_integers ==3

In [17]:
is_equal_to_3[:5]

array([ True, False, False, False, False])

In [18]:
sum(is_equal_to_3)

31

In [19]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

# Exercise 1.04: Continuing Verification of Data Integrity

Vamos continuar no mesmo notebook o exercício

In [20]:
dupe_mask = id_counts == 2

In [21]:
dupe_mask[0:5]

63b20368-1a04    True
51e5ff58-5a0f    True
db903e22-a55a    True
9e6e766d-ba75    True
fa286931-8ded    True
Name: ID, dtype: bool

In [22]:
id_counts.index[0:5]

Index(['63b20368-1a04', '51e5ff58-5a0f', 'db903e22-a55a', '9e6e766d-ba75',
       'fa286931-8ded'],
      dtype='object')

In [23]:
dupe_ids = id_counts.index[dupe_mask]

In [24]:
dupe_ids = list(dupe_ids)

In [25]:
len(dupe_ids)

313

In [26]:
dupe_ids[0:5]

['63b20368-1a04',
 '51e5ff58-5a0f',
 'db903e22-a55a',
 '9e6e766d-ba75',
 'fa286931-8ded']

Feito a lista o próximo passo e analisar a lista de duplicados para ver se tem algo diferente entre eles, para isso usaremos os métodos .isin e .loc que são do DataFrame **df**

In [27]:
df.loc[df['ID'].isin(dupe_ids[0:3]), :]

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
9116   63b20368-1a04     200000    1          3         1   29    -1     -1   
9216   63b20368-1a04          0    0          0         0    0     0      0   
14979  db903e22-a55a      50000    1          2         2   55     2      0   
15079  db903e22-a55a          0    0          0         0    0     0      0   
25588  51e5ff58-5a0f      80000    2          2         1   37     0      0   
25688  51e5ff58-5a0f          0    0          0         0    0     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
9116      -1     -1  ...       8335        971       4278     46722     22985   
9216       0      0  ...          0          0          0         0         0   
14979      0      0  ...      15848      16026      16359      1325      1506   
15079      0      0  ...          0          0          0         0         0   
25588      0      0  ...      45458      48679      49895      5000      3000   
25688      0      0  ...          0          0          0         0         0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
9116       8346       971      4296     21767                           0  
9216          0         0         0         0                           0  
14979       713       582       600       607                           1  
15079         0         0         0         0                           0  
25588      2000      4000      2000      2000                           0  
25688         0         0         0         0                           0  

[6 rows x 25 columns]

Com base na análise dos IDs duplicados, podemos concluir que existe uma linha que contém valores zerados e que precisaremos limpar e utilizaremos uma Matrix Boolean para isso.

In [28]:
df_zero_mask = df == 0

In [29]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)

In [30]:
sum(feature_zero_mask)

315

In [31]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()

In [32]:
df_clean_1.shape

(29685, 25)

In [33]:
df_clean_1['ID'].nunique()

29685

In [34]:
df_clean_1.to_csv('df_clean_1.csv',index=False)

Ao final exportamos o arquivo sem as linhas zeradas e podemos seguir para as próximas etapas.